model:
  base_ckpt: ./pretrained.ckpt
  use_ema_weights: false
  freeze_input: false
  freeze_l1: false
  freeze_l2: false
  freeze_output: false
  l1_size: 256
  l2_size: 32
  l3_size: 32
  lambda_: [1.0]
  lr: [0.1]
  label_smoothing_eps: 0.0
  num_batches_warmup: 2000
  score_scaling: 361
  momentum: 0.0
  gamma: 0.992

data:
  features: HalfKP
  train: ../train.bin
  val: ../val.bin
  smart_fen_skipping: true
  random_fen_skipping: 0
  batch_size: 16384
  num_workers: 8
  threads: 8
  epoch_size: 5000000
  validation_size: 500000

trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 30
  default_root_dir: ./runs/ft/default
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: ./runs/ft
      name: default
      version: ""
